eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: zuul
server:
  port: 7070

zuul:
  routes:
    api1:
      path: /client/**
      service-id: CLIENT1
    api2:
      path: /server/**
      service-id: SERVER1